FROM pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uv/bin/uv

ENV LANG=C.UTF-8
RUN mkdir /app
WORKDIR /app
ADD . /app

# Install dependencies using uv
RUN /uv/bin/uv pip install --system -r requirements.txt

# Entry point
CMD ["python", "ppo/train_ppo.py"]
